:four_leaf_clover: Require changelog

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -183,11 +183,9 @@ jobs:
             tag=${tag:-"$(git describe --tags 2>/dev/null | grep -E '^v.*' || true)"}
             echo "git tag is $(git describe --tags 2>/dev/null | grep -E '^v.*' || true)"
             /tmp/workspace/release/dockmoor-linux_amd64 --version
-            release_commit_msg="$(git log -1 --pretty=%B | grep -E "^:gem: Release $tag\$")"
-            if [ ! -z "$release_commit_msg" ]; then
-              echo "This is a commit with generated content, skipping"
-              exit 0
-            fi
+
+            cat CHANGELOG.md | grep "## $tag" || echo "Missing Changelog entry for $tag"
+
             if [ ! -z "$tag" ]; then
               ghr -t "$GITHUB_TOKEN" -u "$CIRCLE_PROJECT_USERNAME" -r "$CIRCLE_PROJECT_REPONAME" --replace "$tag" /tmp/workspace/release/
             else
