:construction_worker: simulate_release

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -10,7 +10,7 @@ jobs:
 
   build:
     name: Build
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-18.04
     steps:
 
       - name: Set up Go 1.12.16
@@ -86,3 +86,69 @@ jobs:
       - name: Cross-compile
         run: cd cmd/dockmoor && GO111MODULE=on /home/runner/go/bin/gox -os="darwin linux windows" -arch="amd64" -output "../../release/dockmoor-{{.OS}}_{{.Arch}}"
 
+  release:
+    name: Publish
+    runs-on: ubuntu-18.04
+    if: startsWith(github.ref, "refs/tags/v")
+    steps:
+      - name: Get the version
+        id: get_version
+        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
+      - name: Verify CHANGELOG contains release tag
+        run: |
+          tag=$GITHUB_REF # refs/heads/feature-branch-1
+          if ! cat CHANGELOG.md | grep "## $tag" ; then
+            echo "Missing Changelog entry for $tag, refusing to release"
+            exit 1
+          fi
+
+  simulate_release:
+    name: Simulate Release
+    runs-on: ubuntu-18.04
+    if: !startsWith(github.ref, "refs/tags/v")
+    steps:
+      - name: Install
+        run: |
+           sudo apt-get install ruby \
+             && sudo gem install asciidoctor
+          wget https://github.com/jgm/pandoc/releases/download/2.4/pandoc-2.4-1-amd64.deb \
+            && sudo dpkg -i pandoc-2.4-1-amd64.deb
+      - name: Get the version
+        id: get_version
+        run: echo ::set-output name=VERSION::${GITHUB_REF##*/}
+      - name: Update README.adoc
+        run: |
+          set -v
+          tag=${{ steps.tag.outputs.result }}
+
+          git config --global user.email "$GIT_EMAIL"
+          git config --global user.name "$GIT_USER"
+
+          # Switch to master and reset to current commit
+          digest=$(git rev-parse HEAD)
+          git checkout -b master 2>/dev/null || git checkout master
+          git reset --hard $digest
+
+          (cd cmd/dockmoor/doc && ./generate.sh)
+
+          set +v
+          echo "START README.adoc"
+          cat README.adoc
+          echo "END README.adoc"
+
+          set -v
+
+          git add README.adoc
+          # --allow-empty for rebuilds without release
+          git commit --allow-empty -m ":gem: Simulate Release"
+
+          git push --force-with-lease --dry-run origin master --tags
+
+          # Forward developer to master
+          digest=$(git rev-parse HEAD)
+          git checkout -b develop 2>/dev/null || git checkout develop
+          git reset --hard $digest
+          git push --dry-run origin develop
+        env:
+          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
+          GIT_USER: ${{ secrets.GIT_USER }}
